#!/usr/bin/env Rscript
#------------------------------------------------#
#         Generate and plot IBS statistics:      # 
#              R0, R1, and KING robust           #
#------------------------------------------------#

# Input files and variables
# -------------------------------------------------------------------------------------------------- #
# indir - Path to input directory containing the .count output file of SNPDuo
# inprefix - Prefix name of the .count input file from SNPDuo
# outprefix - Prefix name of output files (plots)

indir = "/path/to/input/directory"
inprefix = "prefix_of_input_file"
outprefix = "prefix_of_output_file"
# -------------------------------------------------------------------------------------------------- #

# Install required packages
# install.packages(c("ggplot2", "ggrepel", "readr", "dyplr"))

# Load libraries
library(ggplot2)
library(ggrepel)
library(readr)
library(dyplr)

# Set output folder
setwd(indir)

# Input files are .count and .summary files generated by SNPDuo
count_data <- read_csv(paste0(inprefix, ".count"), col_names = TRUE)
colnames(count_data) <- c("FID1", "IID1", "FID2", "IID2", "IBS0", "IBS1", "IBS2", "IBS2het")

# Calculate R1 statistics
count_data$R1 <- count_data$IBS2het/(count_data$IBS1 + count_data$IBS0)
# Calculate the log10 of R1 stat
count_data$logR1 <- log10(count_data$R1)

# Calculate R0 statistics
count_data$R0 <- count_data$IBS0/count_data$IBS2het

# Calculate KING robust
count_data$KING <- (count_data$IBS2het - (2 * count_data$IBS0)) / (count_data$IBS1 + (2 * count_data$IBS2het))

# Find clone pairs based on R1 value
count_data$relation <- "unknown"
count_data$relation[count_data$logR1 > 0] <- "clone"

# write the list of clone pairs and relative IBS statistics
clone_ibs <- count_data[count_data$logR1 > 0, 1 : (ncol(count_data) -2)]
write.table(clone_ibs, 
    paste0(indir, "/", outprefix, "_clones.txt"), 
    sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)

# Create two layers to plot to emphasize the color and dot size of the known relationships
count_data$size <- 2.5
count_data$size[count_data$relation == "unknown"] <- 1.5
df_layer_1 <- count_data[count_data$relation == "unknown" ,]
df_layer_2 <- subset(count_data, subset = relation %in% c("clone"))

# Plot KINGrobust vs. log10 R1
outKING <- paste0(outprefix, "_KING_log10R1.pdf")
p1 <- ggplot() + 
    geom_point(
        data = df_layer_1,
        aes(x = logR1, y = KING),
        shape = 21, color = "black",
        fill = "azure2", alpha = 0.5,
        size = df_layer_1$size) +
    geom_point(
        data = df_layer_2, 
        aes(x = logR1, y = KING, fill = relation), 
        shape = 21, color = "black", alpha = 0.5, 
        size = df_layer_2$size) +
        scale_fill_manual(values = c( "clone" = "blue")) +
        scale_x_continuous(
          breaks = round(seq(min(count_data$logR1), max(count_data$logR1), 0.4), 1),
          name = expression(Log[10](R1))) +
        scale_y_continuous(
          breaks = round(seq(min(count_data$KING), max(count_data$KING), 0.2), 1),
          name = "KING Robust")

ggsave(outKING, p1)

# Plot R0 vs. log10 R1
outR0 <- paste0(outprefix, "_R0_log10R1.pdf")
p2 <- ggplot() + 
    geom_point(
        data = df_layer_1,
        aes(x = logR1, y = R0),
        shape = 21, color = "black",
        fill = "azure2", alpha = 0.5,
        size = df_layer_1$size) +
    geom_point(
        data = df_layer_2, 
        aes(x = logR1, y = R0, fill = relation), 
        shape = 21, color = "black", alpha = 0.5, 
        size = df_layer_2$size) +
        scale_fill_manual(values = c( "clone" = "blue")) +
        scale_x_continuous(
          breaks = round(seq(min(count_data$logR1), max(count_data$logR1), 0.4), 1),
          name = expression(Log[10](R1))) +
        scale_y_continuous(
          breaks = round(seq(min(count_data$R0), max(count_data$R0), 2), 1),
          name = "R0")

ggsave(outR0, p2)
