#!/usr/bin/env Rscript
#--------------------------------------------------------------------------------#
#      Root phylogenetic tree generated with Embassy tool and visualize it.      #
#        Zoom in the clade of P. dactylifera and visualize the subtree           #
#                   with labelled tips for closer evaluation.                    #
#--------------------------------------------------------------------------------#

# Input files and variables
# ---------------------------------------------------------------------------------------------- #
# INDIR - Path to the input directory containing the phylogenetic tree in Newick format
# TREE_FILE - Phylogenetic tree file name (Newick format)
# GROUP_FILE - Text file containing the sample labels generated by VCF2Dis, the original sample names 
# and the group information (e.g. female from North Africa)

INDIR = "/path/to/input/directory/with/phylo/tree"
TREE_FILE = "tree_file.nwk"
GROUP_FILE = "text_file_with_label_and_group_info"
# ---------------------------------------------------------------------------------------------- #

# Install required packages
# install.packages(c("ape", "ggtree", "treeio", "tidytree"))

# Load required libraries
library(ape)
library(ggtree)
library(treeio) # Required for S4 tree objects
library(tidytree)

setwd(INDIR)

# Read the Newick tree generated with fneighbor (Embassy) as a "phylo" object
tree <- read.tree(TREE_FILE)

# Read chain file with new names
group_info <- read.table(GROUP_FILE, header = TRUE, stringsAsFactors = FALSE)

# Rename VCF2Dis labels with final labels from group_info
tree_renamed <- rename_taxa(tree, group_info, vcf2dis_name, final_label)

# Root the tree using P. canariensis as the outgroup
out_group <- grep("^P_can", tree_renamed$tip.label, value = TRUE)
tree_renamed <- root(tree_renamed, outgroup = out_group, resolve.root = TRUE)

# Add group info and rename internal branches
final_tree <- full_join(tree_renamed, group_info, join_by("label" == "label"))
final_tree@extraInfo$group[is.na(final_tree@extraInfo$group)] <- "ZZBranches"

# Visualize the whole rooted tree using rectangular layout (no tip labels)
g <- ggtree(final_tree, aes(color = group), linewidth = 0.2, show.legend = FALSE) +
       # geom_tiplab(aes(label = label), size = 2, linesize = 0.1, show.legend = FALSE) + # Add tip labels
       geom_tippoint(aes(color = group), size = 0.3) + # Add solid circles at the tips
       scale_color_manual(values = c("magenta2", "gold1", "orange1", "firebrick3", "darkred", "chocolate3", "blue2", "dodgerblue1", "forestgreen", "darkmagenta", "black"),
                          labels = c("P. atlantica", "P. canariensis", "female", "female Egypt/Sudan NCBI", "female North Africa NCBI", "female Middle East/West Asia NCBI", "male", "male NCBI", "P. sylvestris", "P. theophrasti", ""),
                          name = "") +
       theme_tree() + 
       theme(legend.position = "bottom")
	   # + geom_text2(aes(label = node), size = 0.3) # Add node labels

# Save tree pdf file
ggsave(sub(".mat", ".pdf", TREE_FILE), g)

# Zoom on the P. dactylifera clade (Extract clade 277)
sub_tree <- tree_subset(final_tree, node = 277, levels_back = 0)

# Visualize the tree subset using rectangular layout and printing tip labels
g_zoom <- ggtree(sub_tree, aes(color = group.y), branch.length='none', linewidth = 0.2, show.legend = FALSE) + 
            geom_tiplab(aes(label = label), size = 1.5, show.legend = FALSE) + # Add tip labels
            geom_tippoint(aes(color = group.y), size = 0.25) + # Add solid circles at the tips
            # geom_nodelab(aes(subset = !isTip, label = node), hjust = -0.1, color = "red", size = 1) + # Add node labels
			scale_color_manual(values = c("magenta2", "orange1", "firebrick3", "darkred", "chocolate3", "blue2", "dodgerblue1", "black"),
                               labels = c("P. atlantica", "female", "female Egypt/Sudan NCBI", "female North Africa NCBI", "female Middle East/West Asia NCBI", "male", "male NCBI", ""),
                               name = "") +
			theme_tree() + 
			theme(legend.position = "bottom")

# Expand space to prevent label clipping 
g_zoom <- g_zoom + 
      hexpand(ratio = 0.05, direction = 1) +
      vexpand(ratio = 0.1, direction = 1) +
      vexpand(ratio = 0.1, direction = -1)

# Save tree pdf file
ggsave(sub(".mat", "_Pdact_zoom.pdf", TREE_FILE), g_zoom, width = 7, height = 14)
